name: Java CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: '11'
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Test with Gradle
      run: ./gradlew build 
     
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:10})
    
    - name: Docker login
      run: docker login -u="loginmayankvonage" -p="abcd@1983" docker.io
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag loginmayankvonage/mayanktest1:${{steps.vars.outputs.tag}}
   
    - name: Publish dockerimage to docker hub
      run: docker push loginmayankvonage/mayanktest1:${{steps.vars.outputs.tag}}
    
    - name: Build Docker image with latest tag
      run: docker build . --file Dockerfile --tag loginmayankvonage/mayanktest1:latest
    
    - name: Publish dockerimage to docker hub
      run: docker push loginmayankvonage/mayanktest1:latest
