name: Java CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:
      - master

jobs:
  gradleBuild:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '11' ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{matrix.java}}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build 
     
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:10})
    
      - name: Docker login
        run: docker login -u="loginmayankvonage" -p="abcd@1983" docker.io
    
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag loginmayankvonage/mayanktest1:${{steps.vars.outputs.tag}}
   
      - name: Publish dockerimage to docker hub
        run: docker push loginmayankvonage/mayanktest1:${{steps.vars.outputs.tag}}
    
      - name: Build Docker image with latest tag
        run: docker build . --file Dockerfile --tag loginmayankvonage/mayanktest1:latest
    
      - name: Publish dockerimage to docker hub
        run: docker push loginmayankvonage/mayanktest1:latest
